### ISSUE TITLE
Query on Obtaining OBD Data

### ISSUE THREAD

**Issue by Jokin-Phebus** [Justas1988/codec8e-parser-tcp-server#1]
Hello, I just tested your code and it works correctly, thank you very much for the contribution. I have a question, to obtain a value from the OBD, such as the engine revolutions, how could I do it? Thanks again!

**Comment by Justas1988** [comment]
Hello,

I suppose this not code related question, but more about the Teltonika trackers itself.

To pull any OBD data you obviously need OBD reading device like for example FMB003

The rest is just plugging tracker to vehicle OBD port and enabling required I/O elements, for example engine RPM.

Each I/O element has corresponding AVL ID where the value comes. AVL ID list and configuration manual can be found in Teltonika Wiki page.

Have a nice day and good luck 🤞
