### ISSUE TITLE
HOW TO SEND A COMMAND TO A SPECIFIC GH5200

### ISSUE THREAD

**Issue by tm-topnet** [Justas1988/codec8e-parser-tcp-server#2]
HI,
first thanks for this code, it's very useful.
I was wondering if it was possible to send a parameter setting command to a specific device. Let's consider the case in which 3 different devices have connected to this server, how can I choose the device to which to send a parameter setting command?

Thanks

**Comment by Justas1988** [comment]
Hello,

This code does not have command sending functionality, also it is not multithreaded so it will not allow multiple connections at once. This is just a tool to test record sending functionality, not something to be used as a main backend. But still, it is helpful for people who do not have their own backend yet, so at least it's possible to have an idea on how Codec8 communication and parsing works.

Now to answer your question, you can send parameter commands in codec 12 format to the device which already has an open link / thread to your server so you will always know to which device you are sending the command. 

If you do backend programing yourself or you have developers that work for you, it should not be difficult to figure out once you check Teltonika codec documentation:

https://wiki.teltonika-gps.com/view/Codec#Codec_12


Best regards.

**Comment by Justas1988** [comment]
Hello,

This code does not have command sending functionality, also it is not multithreaded so it will not allow multiple connections at once. This is just a tool to test record sending functionality, not something to be used as a main backend. But still, it is helpful for people who do not have their own backend yet, so at least it's possible to have an idea on how Codec8 communication and parsing works.

Now to answer your question, you can send parameter command in codec 12 format to the device which already has an open link / thread to your server so you will always know to which device you are sending the command. 

If you do backend programing yourself or you have developers that work for you, it should not be difficult to figure out once you check Teltonika codec documentation.

https://wiki.teltonika-gps.com/view/Codec#Codec_12
