### ISSUE TITLE
Lat and Long are Not Correct

### ISSUE THREAD

**Issue by eric-lancelot** [Justas1988/codec8e-parser-tcp-server#3]
Hi there,

First i would like to say you have done a tremendous job writing this script it has been helpful for me, the only issue is that the cords( lat and long ) are incorrect.

they come out like this:

longtitude = 326195083
latitude = 5119633

hard to know where the dot ( . ) should be placed.

when i try them in google maps they lead to the black sea and iraq etc.. completely not where i am right now.

**Comment by eric-lancelot** [comment]
Hi got it fixed, here is what i did now the coordinates are working well

`longtitude = avl_data_start[data_field_position:data_field_position+8]
		longitude_value = int(longtitude, 16)
		longitude_decimal = longitude_value / 10000000
		if longitude_value & (1 << 31):
			longitude_decimal *= -1
		print("Longitude (Decimal):", longitude_decimal)
		io_dict["longtitude"] = longitude_decimal
		data_field_position += len(longtitude)
		

		latitude = avl_data_start[data_field_position:data_field_position+8]
		latitude_value = int(latitude, 16)
		latitude_decimal = latitude_value / 10000000
		if latitude_value & (1 << 31):
			latitude_decimal *= -1
		print("Latitude (Decimal):", latitude_decimal)
		io_dict["latitude"] = latitude_decimal
		data_field_position += len(latitude)`

**Comment by Justas1988** [comment]
Hello Eric,

Thanks a lot for positive feedback.

Yes, I'm aware that coordinates are not properly parsed. And I have added your function. However, I need to test it more. With codec 8 packet example I am getting longitude value -429.0261813 which does not look correct as longitude should be between -180 and 180 so this is strange.

Could be that device generated incorrect coordinate, I will try to find out and add proper parsing if required.

Kind regards

**Comment by eric-lancelot** [comment]
Hi Man,

when the devices sends fuel data from a BLE Sensor( AVL IO ID : 270 ) it send it as 0x0000 yet when i connect the same device to another platform it display the actual fuel litres, clearly the issue is with our the script is parsing the fuel data.

according to teltonika the type of data for this AVL IO ID 270 is Unsigned meaning data should be a positive int.

any ideas ?
