### ISSUE TITLE
BLE Fuel data parsing

### ISSUE THREAD

**Issue by eric-lancelot** [Justas1988/codec8e-parser-tcp-server#5]
Hi Man,

when the devices sends fuel data from a BLE Sensor( AVL IO ID : 270 ) it send it as 0x0000 yet when i connect the same device to another platform it display the actual fuel litres, clearly the issue is with how the script is parsing the fuel data.

according to teltonika the type of data for this AVL IO ID 270 is Unsigned meaning data should be a positive int.

any ideas ?

**Comment by Justas1988** [comment]
Hello again,

AVL 270 is not being parsed at all by the script, it is sent as RAW hex value. You can check from line 485 how many elements have functions and you are free to add more.

There are too many different AVLs to add and there is no reason to add them all.

If you have Raw codec 8e packet which according to you has avl 270 value but script does take it, please provide it to me and I will check.

If codec structure is being parsed incorrectly then I will fix it. 

Thank you
